#!/usr/bin/env node
// Parlel — collision-safe `up`.
//
// Brings up the requested services (SERVICES env, comma list or `all`) on local
// Docker, publishing each on its canonical host port. If a canonical port is
// already taken on the host (you have a local Postgres on 5432, say), it
// transparently remaps that ONE service to a free host port and tells you —
// so `SERVICES=all` always succeeds no matter what's running on your machine.
//
// Container ports stay canonical; only the *host* side of a colliding mapping
// changes. Connect with the host port we print (or the canonical one if there
// was no collision).
//
// Usage:
//   SERVICES=all node scripts/up.mjs
//   SERVICES="postgres,redis,stripe" node scripts/up.mjs
//   node scripts/up.mjs postgres redis            # args also work
//
// Pass-through: any extra docker-compose flags after `--`, e.g.
//   node scripts/up.mjs -- --build

import { readFile, readdir, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SERVICES_DIR = join(ROOT, "services");
const GENERATED = join(ROOT, "docker-compose.generated.yml");

// ── parse args / env ─────────────────────────────────────────────────────────
const dashIdx = process.argv.indexOf("--");
const passthrough = dashIdx >= 0 ? process.argv.slice(dashIdx + 1) : [];
const argServices = process.argv
  .slice(2, dashIdx >= 0 ? dashIdx : undefined)
  .filter((a) => !a.startsWith("-"));

async function resolveServices() {
  let names = argServices.length
    ? argServices
    : (process.env.SERVICES || "")
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
  names = names.map((s) => s.toLowerCase());
  if (names.length === 1 && names[0] === "all") {
    names = (await readdir(SERVICES_DIR, { withFileTypes: true }))
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
  }
  if (!names.length) names = ["postgres", "redis"];
  return [...new Set(names)].sort();
}

async function portFor(slug) {
  try {
    const m = JSON.parse(
      await readFile(join(SERVICES_DIR, slug, "manifest.json"), "utf8"),
    );
    return m.protocol === "embedded" ? null : m.port || null;
  } catch {
    return null;
  }
}

// Is a TCP host port free to publish?
function hostPortFree(port) {
  return new Promise((resolve) => {
    const s = createServer();
    s.once("error", () => resolve(false));
    s.once("listening", () => s.close(() => resolve(true)));
    s.listen(port, "0.0.0.0");
  });
}

async function findFreePort(avoid) {
  // Try the ephemeral-ish range above the canonical ports first.
  for (let p = 15000; p < 16000; p++) {
    if (avoid.has(p)) continue;
    if (await hostPortFree(p)) return p;
  }
  // Fall back to an OS-assigned port.
  return new Promise((resolve, reject) => {
    const s = createServer();
    s.once("error", reject);
    s.listen(0, () => {
      const port = s.address().port;
      s.close(() => resolve(port));
    });
  });
}

// ── main ─────────────────────────────────────────────────────────────────────
async function main() {
  const services = await resolveServices();
  const used = new Set();
  const mappings = []; // { slug, hostPort, containerPort, remapped }

  for (const slug of services) {
    const port = await portFor(slug);
    if (!port) continue; // embedded / unknown — no port to publish
    let hostPort = port;
    let remapped = false;
    if (!(await hostPortFree(port)) || used.has(port)) {
      hostPort = await findFreePort(new Set([...used, port]));
      remapped = true;
    }
    used.add(hostPort);
    mappings.push({ slug, hostPort, containerPort: port, remapped });
  }

  if (!mappings.length) {
    console.error("parlel: no services with ports to start.");
    process.exit(1);
  }

  // Generate a compose file publishing only the requested services' ports.
  const portLines = mappings
    .map(
      (m) =>
        `      - "${m.hostPort}:${m.containerPort}"   # ${m.slug}${m.remapped ? " (remapped)" : ""}`,
    )
    .join("\n");

  const compose = `# AUTO-GENERATED by scripts/up.mjs — do not edit. Re-run \`npm run up\`.
services:
  parlel:
    build: .
    image: parlel:local
    environment:
      SERVICES: "${services.join(",")}"
    ports:
${portLines}
`;
  await writeFile(GENERATED, compose);

  // Report the plan, especially any remaps.
  const remapped = mappings.filter((m) => m.remapped);
  console.log(`parlel: starting ${mappings.length} service(s).`);
  if (remapped.length) {
    console.log(
      `parlel: ${remapped.length} host port(s) were busy — remapped to free ports:`,
    );
    for (const m of remapped) {
      console.log(
        `  • ${m.slug}: connect on localhost:${m.hostPort} (container ${m.containerPort})`,
      );
    }
  }

  // Hand off to docker compose.
  const args = ["compose", "-f", GENERATED, "up", "--build", ...passthrough];
  const child = spawn("docker", args, { stdio: "inherit" });
  child.on("exit", (code) => process.exit(code ?? 0));
}

main().catch((err) => {
  console.error(`parlel: ${err?.message || err}`);
  process.exit(1);
});
